mdapipkg/source/objects/Topic__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce Feature</fullName>
                    <default>true</default>
                    <label>Salesforce Feature</label>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Research Topic</fullName>
                </value>
                <value>
                    <fullName>Certification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Topic</label>
    <nameField>
        <label>Topic</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/source/objects/Topic_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Resource__c</fullName>
        <label>Resource</label>
        <referenceTo>Digital_Resource__c</referenceTo>
        <relationshipLabel>Topic Resources</relationshipLabel>
        <relationshipName>Topic_Resources1</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <label>Topic</label>
        <referenceTo>Topic__c</referenceTo>
        <relationshipLabel>Topic Resources</relationshipLabel>
        <relationshipName>Topic_Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Topic Resource</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Topic Resource</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Topic Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/clsTopics.cls
public with sharing class clsTopics {
    public clsTopics() {}

    @AuraEnabled
    public static List<Topic_Resource__c> getAllTopics()
    {

        List<Topic_Resource__c> existingAssignments = [SELECT Id, Topic__r.Name FROM Topic_Resource__c];
        return existingAssignments;

    }
    
    @InvocableMethod(label='Assign Digital Resource to all Salesforce Features' description='' category='Topics')
   public static void assignDigitalResourceToAllSalesforceFeatures(List<Id>  digitalResources) {
     
    Id digitalResource = digitalResources[0];
    List<Topic_Resource__c> existingTopicResource = [SELECT Id FROM Topic_Resource__c WHERE Resource__c = :digitalResource];
    delete existingTopicResource;
      
    List<Topic__c> topics = [SELECT Id FROM Topic__c WHERE Type__c = 'Salesforce Feature'];
    for (Topic__c topic : topics) {
       
      Topic_Resource__c newTopicResource = new Topic_Resource__c();
        newTopicResource.Topic__c = topic.Id;
        newTopicResource.Resource__c = digitalResource;
        existingTopicResource.add(newTopicResource);
      
    }
      
    insert existingTopicResource;
      
  }

    
}